version: '2'

services:
  web:
    image: nginx:1.19.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./src:/usr/share/nginx/html:ro
      - ./conf/site.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx/
    networks:
      - code-network

  php:
    image: php:7.4.11-fpm-alpine3.12
    volumes:
      - ./src:/usr/share/nginx/html
    networks:
      - code-network

  psql:
    image: postgres:9.6-alpine
    environment:
        POSTGRES_PASSWORD: password
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - code-network

networks:
  code-network:
    driver: bridge